### ISSUE TITLE
请问如何获取字幕呢？

### ISSUE THREAD

**Issue by HaloWang** [qiaoxueshi/WWDC_2016_Video_Subtitle#1]
我试着做了如下的事情：
1. 在 Safari 中打开 [Session715](https://developer.apple.com/videos/play/wwdc2016/715/)，但是无法找到任何字幕
2. 在 WWDC 中打开同样的视屏，也没有任何字幕显示，勾选 auto 也没有字幕
   <img width="697" alt="2016-06-20 10 40 58" src="https://cloud.githubusercontent.com/assets/7344724/16181953/97c5abbe-36d3-11e6-88a2-811d6828be43.png">

**Comment by wujichao** [comment]
705还没有呢 apple会陆续更新

**Comment by HaloWang** [comment]
😇 先放视频，字幕陆续更新啊~那我等等吧

**Comment by XueshiQiao** [comment]
@HaloWang 是的 现在就陆陆续续的提供了 如果需要的话，可以参考这个Repo https://github.com/wujichao/WWDC_2016_Video_Subtitle

**Comment by HaloWang** [comment]
我也注意到了，WWDC for mac 上 416 以及之前的 session 好像都有字幕了，另外 youtube 上也有视频可以看（不过晚了不少）
